/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qms_lgu_inf238;


public class Analytics extends javax.swing.JFrame {

    /**
     * Creates new form Analytics
     */
    public static int red = 0;
    public static int blue = 0;
    public static int green = 0;
    public static int yellow = 0;
    public static int violet = 0;
    public static int orange = 0;
    public static int cyan = 0;
    public static int pink = 0;
    
    
    
    
   
    
    public Analytics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        redLabel = new javax.swing.JLabel();
        blueLabel = new javax.swing.JLabel();
        violetLabel = new javax.swing.JLabel();
        pinkLabel = new javax.swing.JLabel();
        greenLabel = new javax.swing.JLabel();
        yellowLabel = new javax.swing.JLabel();
        cyanLabel = new javax.swing.JLabel();
        orangeLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        redLabel.setBackground(new java.awt.Color(255, 0, 0));
        redLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        redLabel.setForeground(new java.awt.Color(255, 255, 255));
        redLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        redLabel.setText("0");
        redLabel.setOpaque(true);
        jPanel1.add(redLabel);
        redLabel.setBounds(60, 140, 550, 25);

        blueLabel.setBackground(new java.awt.Color(0, 0, 204));
        blueLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        blueLabel.setForeground(new java.awt.Color(255, 255, 255));
        blueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blueLabel.setText("0");
        blueLabel.setOpaque(true);
        jPanel1.add(blueLabel);
        blueLabel.setBounds(60, 180, 550, 25);

        violetLabel.setBackground(new java.awt.Color(102, 51, 255));
        violetLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        violetLabel.setForeground(new java.awt.Color(255, 255, 255));
        violetLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        violetLabel.setText("0");
        violetLabel.setOpaque(true);
        jPanel1.add(violetLabel);
        violetLabel.setBounds(60, 340, 560, 25);

        pinkLabel.setBackground(new java.awt.Color(255, 51, 204));
        pinkLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pinkLabel.setForeground(new java.awt.Color(255, 255, 255));
        pinkLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pinkLabel.setText("0");
        pinkLabel.setOpaque(true);
        jPanel1.add(pinkLabel);
        pinkLabel.setBounds(60, 490, 570, 25);

        greenLabel.setBackground(new java.awt.Color(0, 153, 0));
        greenLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        greenLabel.setForeground(new java.awt.Color(255, 255, 255));
        greenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greenLabel.setText("0");
        greenLabel.setOpaque(true);
        jPanel1.add(greenLabel);
        greenLabel.setBounds(60, 230, 550, 25);

        yellowLabel.setBackground(new java.awt.Color(255, 204, 0));
        yellowLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        yellowLabel.setForeground(new java.awt.Color(255, 255, 255));
        yellowLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yellowLabel.setText("0");
        yellowLabel.setOpaque(true);
        jPanel1.add(yellowLabel);
        yellowLabel.setBounds(60, 280, 550, 25);

        cyanLabel.setBackground(new java.awt.Color(51, 204, 255));
        cyanLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cyanLabel.setForeground(new java.awt.Color(255, 255, 255));
        cyanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cyanLabel.setText("0");
        cyanLabel.setOpaque(true);
        jPanel1.add(cyanLabel);
        cyanLabel.setBounds(60, 390, 560, 25);

        orangeLabel.setBackground(new java.awt.Color(255, 153, 51));
        orangeLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        orangeLabel.setForeground(new java.awt.Color(255, 255, 255));
        orangeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orangeLabel.setText("0");
        orangeLabel.setOpaque(true);
        jPanel1.add(orangeLabel);
        orangeLabel.setBounds(60, 440, 560, 25);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qms_lgu_inf238/Data Analytics.png"))); // NOI18N
        backgroundLabel.setText("jLabel3");
        jPanel1.add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 990, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1015, 615);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analytics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    public static javax.swing.JLabel blueLabel;
    public static javax.swing.JLabel cyanLabel;
    public static javax.swing.JLabel greenLabel;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel orangeLabel;
    public static javax.swing.JLabel pinkLabel;
    public static javax.swing.JLabel redLabel;
    public static javax.swing.JLabel violetLabel;
    public static javax.swing.JLabel yellowLabel;
    // End of variables declaration//GEN-END:variables
}
