/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qms_lgu_inf238;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import java.util.Queue;
import java.util.concurrent.TimeUnit;
import java.util.LinkedList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Counter7 extends javax.swing.JFrame {

    public static Queue <String> counter7Data = new LinkedList<>(); //Data for Waiting Table
    public static Queue <String> onHoldData = new LinkedList<>();  //Data for On Hold Table
    public static Queue <String> noShowData = new LinkedList<>();  // Data for No Show Table
    public static Queue <String> transactionData = new LinkedList<>(); // Data for Transaction Type
    public static Queue <String> certificateData = new LinkedList<>(); // Data for Certificate Type
    public static Queue <String> HoldTransactionData = new LinkedList<>(); // Data for Transaction Type Holding Table
    public static Queue <String> HoldCertificateData = new LinkedList<>(); // Data for Certificate Type Holding Table
    public static Queue <Integer> counter7Queue = new LinkedList<>();
    public static Queue <String> counter7Number = new LinkedList<>();
    public static Queue <Integer> numberOfCopiesPrice = new LinkedList<>();
    public static Queue <Integer> HoldNumberOfCopiesPrice = new LinkedList<>();
    public static Queue <String> TotalAmount = new LinkedList<>();
    public static Queue <String> HoldTotalAmount = new LinkedList<>();
    public static int counter7Basis = 1;
    public static int BirthDeathMarriageCertPrice = 155;
    public static int CenomarPrice = 210;
    public static int AmendmentFee = 1000;
    JComboBox<String> comboBox;
    private static long startTime;
    public static Timer timer;
    
     public static void stopTimer(){
            timer.restart();
            timer.stop();
            timeLabel.setText("00:00:00");
            startTime = System.nanoTime();
    }
     
    public void processTimer(){
        
        startTime = System.nanoTime();
        timer = new Timer(1000, new ActionListener() {
         
            @Override
            public void actionPerformed(ActionEvent e) {
               
                long elapsedTime = System.nanoTime() - startTime;
                long hours = TimeUnit.NANOSECONDS.toHours(elapsedTime);
                long minutes = TimeUnit.NANOSECONDS.toMinutes(elapsedTime) % 60;
                long seconds = TimeUnit.NANOSECONDS.toSeconds(elapsedTime) % 60;

                String formattedTime = String.format("%02d:%02d:%02d", hours, minutes, seconds);
                timeLabel.setText(formattedTime);
            }
        }); 
      timer.start(); 
    }
    public Counter7() {
        initComponents();
        
        currentNumberField.setHorizontalAlignment(currentNumberField.CENTER);
       
        nextButton.setEnabled(false);
        finishButton.setEnabled(false);
        stopButton.setEnabled(false);
        holdButton.setEnabled(false);
        noShowButton.setEnabled(false);
        transferButton.setEnabled(false);
        recallButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nextButton = new javax.swing.JButton();
        registryLabel = new javax.swing.JLabel();
        registryClerkName = new javax.swing.JLabel();
        recallButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        WaitingTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        FinishedTable = new javax.swing.JTable();
        startButton = new javax.swing.JButton();
        noShowButton = new javax.swing.JButton();
        processLabel = new javax.swing.JLabel();
        documentLabel = new javax.swing.JLabel();
        documentTypeLabel = new javax.swing.JLabel();
        stopButton = new javax.swing.JButton();
        currentNumberField = new javax.swing.JTextField();
        transactionTypeLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        NoShowTable = new javax.swing.JTable();
        holdButton = new javax.swing.JButton();
        transferButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        OnHoldTable = new javax.swing.JTable();
        transactionLabel = new javax.swing.JLabel();
        registryLabel1 = new javax.swing.JLabel();
        numberOfCopiesLabel = new javax.swing.JLabel();
        registryLabel2 = new javax.swing.JLabel();
        totalAmountLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(3, 4, 94));

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        registryLabel.setForeground(new java.awt.Color(255, 255, 255));
        registryLabel.setText("Cashier Name:");

        registryClerkName.setForeground(new java.awt.Color(255, 255, 255));
        registryClerkName.setText("Asshley Gozar");

        recallButton.setText("Recall");
        recallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recallButtonActionPerformed(evt);
            }
        });

        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Counter 7");

        timeLabel.setEditable(false);
        timeLabel.setText("00:00:00");

        WaitingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Waiting"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(WaitingTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Current Serving");

        FinishedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Finished"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(FinishedTable);

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        noShowButton.setText("No Show");
        noShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noShowButtonActionPerformed(evt);
            }
        });

        processLabel.setForeground(new java.awt.Color(255, 255, 255));
        processLabel.setText("Processing Time:");

        documentLabel.setForeground(new java.awt.Color(255, 255, 255));
        documentLabel.setText("Document Type:");

        documentTypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        documentTypeLabel.setText("Birth Certficate");

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        currentNumberField.setEditable(false);
        currentNumberField.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        transactionTypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        transactionTypeLabel.setText("Request Copy");

        NoShowTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Show"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(NoShowTable);

        holdButton.setText("Hold");
        holdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holdButtonActionPerformed(evt);
            }
        });

        transferButton.setText("Transfer");
        transferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButtonActionPerformed(evt);
            }
        });

        OnHoldTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "On Hold"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(OnHoldTable);

        transactionLabel.setForeground(new java.awt.Color(255, 255, 255));
        transactionLabel.setText("Transaction Type");

        registryLabel1.setForeground(new java.awt.Color(255, 255, 255));
        registryLabel1.setText("No. of Copies:");

        numberOfCopiesLabel.setForeground(new java.awt.Color(255, 255, 255));
        numberOfCopiesLabel.setText("2");

        registryLabel2.setForeground(new java.awt.Color(255, 255, 255));
        registryLabel2.setText("Total Amount:");

        totalAmountLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalAmountLabel.setText("222");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Payment");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(currentNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(registryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(transactionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(documentLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(processLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(timeLabel)
                        .addGap(165, 165, 165))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(transactionTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(documentTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(registryLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(registryLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(registryClerkName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberOfCopiesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(holdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(noShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(transferButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(recallButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(processLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(transactionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(transactionTypeLabel)
                        .addComponent(registryLabel1)
                        .addComponent(numberOfCopiesLabel))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(documentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(documentTypeLabel)
                            .addComponent(registryLabel2)
                            .addComponent(totalAmountLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registryClerkName))
                        .addGap(29, 29, 29))
                    .addComponent(currentNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transferButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(recallButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(holdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(46, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed

        if(!currentNumberField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "There is still Active Customer!");
        }
        else{
            if(counter7Data.isEmpty()){

                JOptionPane.showMessageDialog(this, "Queue Table is Empty");
            }else{
                processTimer();
                currentNumberField.setText(counter7Data.peek());
                transactionTypeLabel.setText(transactionData.peek());
                documentTypeLabel.setText(certificateData.peek());
                ScreenNumbers.counter7Screen.setText(currentNumberField.getText());
                numberOfCopiesLabel.setText(numberOfCopiesPrice.peek().toString());
                if(transactionTypeLabel.getText().equals(Customer.requestCopy) & documentTypeLabel.getText().equals(Customer.birthCert)){
                    int totalPrice = BirthDeathMarriageCertPrice * numberOfCopiesPrice.peek();
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.requestCopy) & documentTypeLabel.getText().equals(Customer.deathCert)){
                    int totalPrice = BirthDeathMarriageCertPrice * numberOfCopiesPrice.peek();
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.requestCopy) & documentTypeLabel.getText().equals(Customer.marriageCert)){
                    int totalPrice = BirthDeathMarriageCertPrice * numberOfCopiesPrice.peek();
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.requestCopy) & documentTypeLabel.getText().equals(Customer.cenomarCert)){
                    int totalPrice = CenomarPrice * numberOfCopiesPrice.peek();
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.amendment) & documentTypeLabel.getText().equals(Customer.birthCert)){
                    int totalPrice = BirthDeathMarriageCertPrice * numberOfCopiesPrice.peek() + AmendmentFee;
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.amendment) & documentTypeLabel.getText().equals(Customer.deathCert)){
                    int totalPrice = BirthDeathMarriageCertPrice * numberOfCopiesPrice.peek() + AmendmentFee;
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.amendment) & documentTypeLabel.getText().equals(Customer.marriageCert)){
                    int totalPrice = BirthDeathMarriageCertPrice * numberOfCopiesPrice.peek() + AmendmentFee;
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.amendment) & documentTypeLabel.getText().equals(Customer.cenomarCert)){
                    int totalPrice = CenomarPrice * numberOfCopiesPrice.peek() + AmendmentFee;
                    totalAmountLabel.setText("₱ " + totalPrice);
                }
                DefaultTableModel waitingModel = (DefaultTableModel)WaitingTable.getModel();
                DefaultTableModel HoldModel = (DefaultTableModel)OnHoldTable.getModel();
                if(counter7Data.contains(currentNumberField.getText())){
                    waitingModel.removeRow(0);
                } else{
                    HoldModel.removeRow(0);
                }
            }
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void recallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recallButtonActionPerformed

        DefaultTableModel HoldModel = (DefaultTableModel)OnHoldTable.getModel();
        if(onHoldData.isEmpty()){
            JOptionPane.showMessageDialog(this, "On Hold Table is Empty");
        }else if(!currentNumberField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Currently Serving " + currentNumberField.getText());
        }else{
            processTimer();
            currentNumberField.setText(onHoldData.poll());
            transactionTypeLabel.setText(HoldTransactionData.poll());
            documentTypeLabel.setText(HoldCertificateData.poll());
            ScreenNumbers.counter7Screen.setText(currentNumberField.getText());
            numberOfCopiesLabel.setText(HoldNumberOfCopiesPrice.peek().toString());
            HoldModel.removeRow(0);
                if(transactionTypeLabel.getText().equals(Customer.requestCopy) & documentTypeLabel.getText().equals(Customer.birthCert)){
                    int totalPrice = BirthDeathMarriageCertPrice * HoldNumberOfCopiesPrice.poll();
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.requestCopy) & documentTypeLabel.getText().equals(Customer.deathCert)){
                    int totalPrice = BirthDeathMarriageCertPrice * HoldNumberOfCopiesPrice.poll();
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.requestCopy) & documentTypeLabel.getText().equals(Customer.marriageCert)){
                    int totalPrice = BirthDeathMarriageCertPrice * HoldNumberOfCopiesPrice.poll();
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.requestCopy) & documentTypeLabel.getText().equals(Customer.cenomarCert)){
                    int totalPrice = CenomarPrice * numberOfCopiesPrice.poll();
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.amendment) & documentTypeLabel.getText().equals(Customer.birthCert)){
                    int totalPrice = BirthDeathMarriageCertPrice * HoldNumberOfCopiesPrice.poll() + AmendmentFee;
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.amendment) & documentTypeLabel.getText().equals(Customer.deathCert)){
                    int totalPrice = BirthDeathMarriageCertPrice * HoldNumberOfCopiesPrice.poll() + AmendmentFee;
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.amendment) & documentTypeLabel.getText().equals(Customer.marriageCert)){
                    int totalPrice = BirthDeathMarriageCertPrice * HoldNumberOfCopiesPrice.poll() + AmendmentFee;
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.amendment) & documentTypeLabel.getText().equals(Customer.cenomarCert)){
                    int totalPrice = CenomarPrice * HoldNumberOfCopiesPrice.poll() + AmendmentFee;
                    totalAmountLabel.setText("₱ " + totalPrice);
                }
        }
    }//GEN-LAST:event_recallButtonActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed

        if(currentNumberField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No Current Serving!");
        }else{

            if(!counter7Data.contains(currentNumberField.getText())){

                DefaultTableModel HoldModel = (DefaultTableModel)OnHoldTable.getModel();
                if(HoldModel.getRowCount() == -1){
                    JOptionPane.showMessageDialog(this, "On Hold Table is Empty");
                }else{
                    String ticketNumbers = currentNumberField.getText();
                    Object[]row = {ticketNumbers};

                    DefaultTableModel FinishedModel = (DefaultTableModel)Counter7.FinishedTable.getModel();
                    counter7Queue.add(counter7Basis);
                    DefaultTableModel counter = (DefaultTableModel)Counter8.WaitingTable.getModel();
                    counter7Number.add("G-"+counter7Queue.peek().toString());
                    Counter8.counter8Data.add(counter7Number.peek());
                    Object[]counterRow6 = {counter7Number.peek()};
                    counter.addRow(counterRow6);

                    counter7Queue.poll();
                    counter7Number.poll();
                    counter7Basis++;
                    FinishedModel.addRow(row);
                    timer.restart();
                    timer.stop();
                    timeLabel.setText("00:00:00");
                    startTime = System.nanoTime();
                    Counter8.transactionData.add(transactionLabel.getText());
                    Counter8.certificateData.add(documentTypeLabel.getText());
                    Counter8.numberOfCopiesPrice.add(numberOfCopiesLabel.getText());
                    currentNumberField.setText("");
                    transactionTypeLabel.setText("");
                    ScreenNumbers.counter7Screen.setText("--");
                    documentTypeLabel.setText("");
                    totalAmountLabel.setText("");
                    numberOfCopiesLabel.setText("");
                    

                }
            }else{
                String ticketNumbers = counter7Data.peek();
                Object[]row = {ticketNumbers};
                DefaultTableModel model = (DefaultTableModel)Counter7.FinishedTable.getModel();
                if(WaitingTable.getRowCount() == -1){
                    JOptionPane.showMessageDialog(this, "Waiting Table is Empty");
                }else{
                    model.addRow(row);

                    if(counter7Data.isEmpty()){
                        JOptionPane.showMessageDialog(this, "Queue is Empty");
                    }else{

                        counter7Queue.add(counter7Basis);
                        DefaultTableModel counter = (DefaultTableModel)Counter8.WaitingTable.getModel();
                        counter7Number.add("G-"+counter7Queue.peek().toString());
                        Counter8.counter8Data.add(counter7Number.peek());
                        Object[]counterRow8 = {counter7Number.peek()};
                        counter.addRow(counterRow8);

                        counter7Queue.poll();
                        counter7Number.poll();
                        counter7Basis++;
                        timer.restart();
                        timer.stop();
                        timeLabel.setText("00:00:00");
                        startTime = System.nanoTime();
                        transactionTypeLabel.setText("");
                        documentTypeLabel.setText("");
                        totalAmountLabel.setText("");
                        numberOfCopiesLabel.setText("");
                        ScreenNumbers.counter7Screen.setText("--");
                        Counter8.transactionData.add(transactionData.poll());
                        Counter8.certificateData.add(certificateData.poll());
                        Counter8.numberOfCopiesPrice.add(numberOfCopiesPrice.poll().toString());
                        counter7Data.poll();
                        currentNumberField.setText("");
                    }
                }
            }
        }
    }//GEN-LAST:event_finishButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed

        if(counter7Data.isEmpty()){
            JOptionPane.showMessageDialog(this, "No Serving Yet!");
        }else{
            processTimer();
            currentNumberField.setText(counter7Data.peek());
            transactionTypeLabel.setText(transactionData.peek());
            documentTypeLabel.setText(certificateData.peek());
            ScreenNumbers.counter7Screen.setText(currentNumberField.getText());
            numberOfCopiesLabel.setText(numberOfCopiesPrice.peek().toString());
            DefaultTableModel waitingModel = (DefaultTableModel)WaitingTable.getModel();
            //Price Conditions and Formula
            if(transactionTypeLabel.getText().equals(Customer.requestCopy) & documentTypeLabel.getText().equals(Customer.birthCert)){
                    int totalPrice = BirthDeathMarriageCertPrice * numberOfCopiesPrice.peek();
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.requestCopy) & documentTypeLabel.getText().equals(Customer.deathCert)){
                    int totalPrice = BirthDeathMarriageCertPrice * numberOfCopiesPrice.peek();
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.requestCopy) & documentTypeLabel.getText().equals(Customer.marriageCert)){
                    int totalPrice = BirthDeathMarriageCertPrice * numberOfCopiesPrice.peek();
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.requestCopy) & documentTypeLabel.getText().equals(Customer.cenomarCert)){
                    int totalPrice = CenomarPrice * numberOfCopiesPrice.peek();
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.amendment) & documentTypeLabel.getText().equals(Customer.birthCert)){
                    int totalPrice = BirthDeathMarriageCertPrice * numberOfCopiesPrice.peek() + AmendmentFee;
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.amendment) & documentTypeLabel.getText().equals(Customer.deathCert)){
                    int totalPrice = BirthDeathMarriageCertPrice * numberOfCopiesPrice.peek() + AmendmentFee;
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.amendment) & documentTypeLabel.getText().equals(Customer.marriageCert)){
                    int totalPrice = BirthDeathMarriageCertPrice * numberOfCopiesPrice.peek() + AmendmentFee;
                    totalAmountLabel.setText("₱ " + totalPrice);
                }else if(transactionTypeLabel.getText().equals(Customer.amendment) & documentTypeLabel.getText().equals(Customer.cenomarCert)){
                    int totalPrice = CenomarPrice * numberOfCopiesPrice.peek() + AmendmentFee;
                    totalAmountLabel.setText("₱ " + totalPrice);
                }
            waitingModel.removeRow(0);
            startButton.setEnabled(false);
            nextButton.setEnabled(true);
            finishButton.setEnabled(true);
            stopButton.setEnabled(true);
            holdButton.setEnabled(true);
            noShowButton.setEnabled(true);
            transferButton.setEnabled(true);
            recallButton.setEnabled(true);
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void noShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noShowButtonActionPerformed

         if(currentNumberField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No Current Serving!");
        }else{
            
            if(!counter7Data.contains(currentNumberField.getText())){
                
            String noShowNumber = currentNumberField.getText();
            noShowData.add(noShowNumber);
            currentNumberField.setText("");
            timer.restart();
            timer.stop();
            timeLabel.setText("00:00:00");
            startTime = System.nanoTime();
            transactionTypeLabel.setText("");
            ScreenNumbers.counter7Screen.setText("--");
            documentTypeLabel.setText("");
            numberOfCopiesLabel.setText("");
            Object[]row = {noShowNumber};
            DefaultTableModel NoShowModel = (DefaultTableModel)NoShowTable.getModel();
            NoShowModel.addRow(row);
            
            }else{
                
            String noShowNumber = currentNumberField.getText();
            noShowData.add(noShowNumber);
            counter7Data.poll();
            currentNumberField.setText("");
             timer.restart();
             timer.stop();
             timeLabel.setText("00:00:00");
             startTime = System.nanoTime();
            transactionTypeLabel.setText("");
            documentTypeLabel.setText("");
            numberOfCopiesLabel.setText("");
            ScreenNumbers.counter7Screen.setText("--");
            transactionData.poll();
            certificateData.poll();
            numberOfCopiesPrice.poll();
            Object[]row = {noShowNumber};
            DefaultTableModel NoShowModel = (DefaultTableModel)NoShowTable.getModel();
            NoShowModel.addRow(row);
            }
        } 
    }//GEN-LAST:event_noShowButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed

        if(!currentNumberField.getText().isEmpty()){
          JOptionPane.showMessageDialog(this, "There is still active cutomer!");
      }else{
        nextButton.setEnabled(false);
        finishButton.setEnabled(false);
        stopButton.setEnabled(false);
        holdButton.setEnabled(false);
        noShowButton.setEnabled(false);
        transferButton.setEnabled(false);
        recallButton.setEnabled(false);
        startButton.setEnabled(true);
       }
    }//GEN-LAST:event_stopButtonActionPerformed

    private void holdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holdButtonActionPerformed

        if(currentNumberField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No Current Serving");
        }else{
            
            if(!counter7Data.contains(currentNumberField.getText())){
                
                String onHoldNumbers =  currentNumberField.getText();
        
                Object[]row = {onHoldNumbers};
                DefaultTableModel HoldModel = (DefaultTableModel)OnHoldTable.getModel();
                HoldModel.addRow(row);
        
                timer.restart();
                timer.stop();
                timeLabel.setText("00:00:00");
                startTime = System.nanoTime();
                onHoldData.add(onHoldNumbers);
                HoldTransactionData.add(transactionTypeLabel.getText());
                HoldCertificateData.add(documentTypeLabel.getText());
                int parsing = Integer.parseInt(numberOfCopiesLabel.getText());
                HoldNumberOfCopiesPrice.add(parsing);
                transactionTypeLabel.setText("");
                documentTypeLabel.setText("");
                currentNumberField.setText("");
                totalAmountLabel.setText("");
                numberOfCopiesLabel.setText("");
                
            }else{
                String onHoldNumbers =  counter7Data.poll();
        
                Object[]row = {onHoldNumbers};
                DefaultTableModel HoldModel = (DefaultTableModel)OnHoldTable.getModel();
                HoldModel.addRow(row);
        
                timer.restart();
                timer.stop();
                timeLabel.setText("00:00:00");
                startTime = System.nanoTime();
                onHoldData.add(onHoldNumbers);
                transactionTypeLabel.setText("");
                documentTypeLabel.setText("");
                currentNumberField.setText("");
                totalAmountLabel.setText("");
                numberOfCopiesLabel.setText("");
                HoldTransactionData.add(transactionData.poll());
                HoldCertificateData.add(certificateData.poll());
                HoldNumberOfCopiesPrice.add(numberOfCopiesPrice.poll());
            }
        }
    }//GEN-LAST:event_holdButtonActionPerformed

    private void transferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButtonActionPerformed

        if(currentNumberField.getText().isEmpty()){
          JOptionPane.showMessageDialog(this, "Current Serving is Empty!");
      }else{
        Transfer.invoker = 2;
        new Transfer().setVisible(true);

         } 
    }//GEN-LAST:event_transferButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Counter7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Counter7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Counter7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Counter7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Counter7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable FinishedTable;
    public static javax.swing.JTable NoShowTable;
    public static javax.swing.JTable OnHoldTable;
    public static javax.swing.JTable WaitingTable;
    public static javax.swing.JTextField currentNumberField;
    private javax.swing.JLabel documentLabel;
    public static javax.swing.JLabel documentTypeLabel;
    private javax.swing.JButton finishButton;
    private javax.swing.JButton holdButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton noShowButton;
    public static javax.swing.JLabel numberOfCopiesLabel;
    private javax.swing.JLabel processLabel;
    private javax.swing.JButton recallButton;
    private javax.swing.JLabel registryClerkName;
    private javax.swing.JLabel registryLabel;
    private javax.swing.JLabel registryLabel1;
    private javax.swing.JLabel registryLabel2;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    private static javax.swing.JTextField timeLabel;
    public static javax.swing.JLabel totalAmountLabel;
    private javax.swing.JLabel transactionLabel;
    public static javax.swing.JLabel transactionTypeLabel;
    private javax.swing.JButton transferButton;
    // End of variables declaration//GEN-END:variables
}
